/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ContractAddresses_5 } from './5'
export type ContractAddressesKey = keyof typeof ContractAddresses
export const ContractAddresses = {
  5: ContractAddresses_5
}